job('First-Maven-Project-Via-DSL') {
    description("First Maven job generated by the DSL on ${new Date()}, the project is a small Maven project hosted on github")
    scm {
        git("https://github.com/SaurabhK65/Jenkins_Upgradev3.git", 'master')
    }
    triggers {
        scm('* * * * *')
    }
    steps {
        maven('mvn -f maven-samples/single-module/pom.xml clean package')
    }
    publishers {
        //archive the war file generated
        archiveArtifacts '**/*.jar'
    }
}
